### ISSUE TITLE
All of sudden this action is failing for me 

### ISSUE THREAD

**Issue by pinalbhatt** [FranzDiebold/github-env-vars-action#57]
All of sudden this action is failing for me. it was working fine till yesterday. 

`Current runner version: '2.275.1'
Runner name: 'gha-runner-signup-team-qat[2](https://github.com/***/user-profile/actions/runs/4831889357/jobs/8609933726#step:1:2)-69dd78bdc4-f6v8c'
Runner group name: 'growth'
Machine name: 'gha-runner-signup-team-qat2-69dd78bdc4-f6v8c'
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'FranzDiebold/github-env-vars-action@v2'
Download action repository 'actions/checkout@v[3](https://github.com/***/user-profiletions/runs/4831889357/jobs/8609933726#step:1:3).[5](https://github.com/***/user-profile/actions/runs/4831889357/jobs/8609933726#step:1:5).2'
Download action repository 'actions/setup-node@v3.[6](https://github.com/***/user-profile/actions/runs/4831889357/jobs/8609933726#step:1:6).0'
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load FranzDiebold/github-env-vars-action/v2/action.yml`

**Comment by FranzDiebold** [comment]
Hi @pinalbhatt ,

I cannot reproduce the error you described, see also [this action run](https://github.com/FranzDiebold/github-env-vars-action/actions/runs/4853456018/jobs/8649645646).

Could you provide the following things?

- [ ] the workflow file you used
- [ ] a better formatted, **complete** error log

**Comment by FranzDiebold** [comment]
Hi @pinalbhatt,

any news regarding the issue and my questions above?

**Comment by FranzDiebold** [comment]
Closing due to inactivity.

**Comment by pinalbhatt** [comment]
sorry for the late response but, I had to update the runner version for my self-hosted runner. Upgrading the runner version fixed the issue.

**Comment by FranzDiebold** [comment]
Thanks for the information @pinalbhatt !
